remote_theme: "mmistakes/minimal-mistakes"
title: "My Personal Blog"
description: "A blog about my thoughts and experiences."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

author:
  name: "Your Name"
  email: "your-email@example.com"
  twitter: "yourusername"

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Theme customization
theme:
  name: "minimal-mistakes"
  skin: "default" # Skins: air, aqua, contrast, dark, dirt, neon, plum, sun
  minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "plum", "sun"
  layout: "single"
  classes: "wide"
  header:
    overlay_color: "#333"
    overlay_filter: "0.5"
    overlay_image: "/assets/images/banner.jpg"
  footer:
    profile_image: "/assets/images/profile.jpg"
    profile_link: "https://yourusername.github.io"

# Navigation Bar
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "About"
    url: "/about/"
